/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectopolilacolonia.Alumno;
import proyectopolilacolonia.Contacto;

/**
 *
 * @author Pablo2
 */
public class Alumno_Contactos extends javax.swing.JFrame {

    private ResultSet rs = null;
    
    
    public Alumno_Contactos() {
        initComponents();
        
        this.refrescarAlumnos();
    }
    
    private void refrescarAlumnos() {
        Alumno a1 = new Alumno();
        
        DefaultTableModel modelo = (DefaultTableModel) this.JTable_alumnos.getModel();
        modelo.setRowCount(0);
        
        rs = a1.List();
        
        int cantCols = modelo.getColumnCount();
        
        try {
            while(rs.next()) {
                Object[] fila = new Object[cantCols];
                
                fila[0]= rs.getObject(2);
                fila[1]= rs.getObject(4);
                fila[2]= rs.getObject(5);
                
                modelo.addRow(fila);
                        
            }
        } catch (Exception e) {
        }
        
        
        
    }
    
    private void refrescarContactos() {
        
        int alumnoFila = this.JTable_alumnos.getSelectedRow();
        String alumnoDni = this.JTable_alumnos.getValueAt(alumnoFila, 0).toString();
        
        Alumno a1 = new Alumno();
        DefaultTableModel modelo = (DefaultTableModel) this.JTable_contactos.getModel();
        modelo.setRowCount(0);
        
        int cantCols = modelo.getColumnCount();
        
        rs = a1.listContacts(alumnoDni);
        
        try {
            while(rs.next()) {
                Object[] fila = new Object[cantCols];
                
                for (int i = 0; i < cantCols; i++) {
                    fila[i] = rs.getObject(i+1);
                }
                
                modelo.addRow(fila);
            }
        } catch (Exception e) {
        }
        
        
        
    }
    
    private void limpiarCampos() {
        
        this.TxtField_nombre.setText("");
        this.TxtField_telefono.setText("");
        this.CBox_vinculo.setSelectedIndex(0);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TxtField_buscarDni = new javax.swing.JTextField();
        Btn_buscarDni = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_alumnos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtField_nombre = new javax.swing.JTextField();
        TxtField_telefono = new javax.swing.JTextField();
        CBox_vinculo = new javax.swing.JComboBox<>();
        Btn_registrar = new javax.swing.JButton();
        Btn_editar = new javax.swing.JButton();
        Btn_eliminar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTable_contactos = new javax.swing.JTable();
        Btn_cerrar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Buiscar alumno por DNI:");

        TxtField_buscarDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtField_buscarDniKeyTyped(evt);
            }
        });

        Btn_buscarDni.setText("Buscar");
        Btn_buscarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_buscarDniActionPerformed(evt);
            }
        });

        jLabel2.setText("Listado de alumnos:");

        JTable_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DNI", "Nombre y apellido", "Fecha de nacimiento"
            }
        ));
        JTable_alumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_alumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable_alumnos);

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel3.setText("(El contacto se guardará en el alumno seleccionado)");

        jLabel4.setText("Datos de contacto:");

        jLabel5.setText("Nombre y apellido:");

        jLabel6.setText("Teléfono:");

        jLabel7.setText("Vínculo");

        TxtField_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtField_nombreKeyTyped(evt);
            }
        });

        TxtField_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtField_telefonoKeyTyped(evt);
            }
        });

        CBox_vinculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madre/Padre", "Hermano/a", "Tío/a", "Primo/a", "Marido/esposa", "Abuelo/a", "Amigo/a" }));

        Btn_registrar.setText("Registrar");
        Btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_registrarActionPerformed(evt);
            }
        });

        Btn_editar.setText("Editar");
        Btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_editarActionPerformed(evt);
            }
        });

        Btn_eliminar.setText("Eliminar");
        Btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_eliminarActionPerformed(evt);
            }
        });

        JTable_contactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nº", "Nombre del alumno", "Nombre del contacto", "Teléfono", "Vínculo"
            }
        ));
        JTable_contactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_contactosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(JTable_contactos);

        Btn_cerrar.setText("Cerrar");
        Btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtField_telefono)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CBox_vinculo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(TxtField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtField_buscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_buscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Btn_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtField_buscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_buscarDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CBox_vinculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_registrar)
                    .addComponent(Btn_editar)
                    .addComponent(Btn_eliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_buscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_buscarDniActionPerformed
        
        if(this.TxtField_buscarDni.getText().trim() == "") {
            JOptionPane.showMessageDialog(this, "¡El campo no puede estar vacio!", "¡Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            
            int cantRows = this.JTable_alumnos.getModel().getRowCount();
            int cantCols = this.JTable_alumnos.getModel().getColumnCount();
            String dni = this.TxtField_buscarDni.getText().trim();
            
            for (int i = 0; i < cantRows; i++) {
                for (int j = 0; j < cantCols; j++) {
                    
                    if(this.JTable_alumnos.getValueAt(i, j).toString().equalsIgnoreCase(dni)) {
                        this.JTable_alumnos.setRowSelectionInterval(i, i);
                    }
                    
                }
            }
                   
            
        }
        
    }//GEN-LAST:event_Btn_buscarDniActionPerformed

    private void Btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_registrarActionPerformed
        if(this.TxtField_nombre.getText().trim() == "" || this.TxtField_telefono.getText().trim() == "") {
            JOptionPane.showMessageDialog(this, "¡Los campos no pueden estar vacios!", "¡Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            
            int fila = this.JTable_alumnos.getSelectedRow();
            String dni = this.JTable_alumnos.getValueAt(fila, 0).toString();
            
            Alumno a1 = new Alumno();
            a1 = a1.find(dni);
            
            Contacto c1 = new Contacto();
            c1.setNombreContacto(this.TxtField_nombre.getText().trim());
            c1.setTelefono(this.TxtField_telefono.getText().trim());
            c1.setVinculo(this.CBox_vinculo.getSelectedItem().toString());
            
            a1.saveContact(a1.getId(), c1);
            
            this.refrescarContactos();
            this.limpiarCampos();
            
        }
    }//GEN-LAST:event_Btn_registrarActionPerformed

    private void JTable_alumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_alumnosMouseClicked
        
        this.refrescarContactos();
        
        
    }//GEN-LAST:event_JTable_alumnosMouseClicked

    private void Btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_editarActionPerformed
        int fila = this.JTable_contactos.getSelectedRow();
        
        Contacto c1 = new Contacto();
        c1.setId(Integer.parseInt(this.JTable_contactos.getValueAt(fila, 0).toString()));
        c1.setNombreContacto(this.TxtField_nombre.getText().trim());
        c1.setTelefono(this.TxtField_telefono.getText().trim());
        c1.setVinculo(this.CBox_vinculo.getSelectedItem().toString());
        
        Alumno a1 = new Alumno();
        a1.updateContact(c1);
        
        this.refrescarContactos();
        this.limpiarCampos();
        
    }//GEN-LAST:event_Btn_editarActionPerformed

    private void JTable_contactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_contactosMouseClicked
        
        int fila = this.JTable_contactos.getSelectedRow();
        
        this.TxtField_nombre.setText(this.JTable_contactos.getValueAt(fila, 2).toString());
        this.TxtField_telefono.setText(this.JTable_contactos.getValueAt(fila, 3).toString());
        String vinculo = this.JTable_contactos.getValueAt(fila, 4).toString();
        
        for (int i = 0; i < this.CBox_vinculo.getItemCount(); i++) {
            if(this.CBox_vinculo.getItemAt(i).toString().equalsIgnoreCase(vinculo)) {
                this.CBox_vinculo.setSelectedIndex(i);
            }
            
        }
        
    }//GEN-LAST:event_JTable_contactosMouseClicked

    private void Btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_eliminarActionPerformed
        
        int resultado = JOptionPane.showConfirmDialog(this, "¿Estás seguro que quieres eliminar este contacto?", "Eliminar Contacto", JOptionPane.YES_NO_OPTION);
        if(resultado == JOptionPane.YES_NO_OPTION) {
            int fila = this.JTable_contactos.getSelectedRow();
            int contactoId = Integer.valueOf(this.JTable_contactos.getValueAt(fila, 0).toString());

            Alumno a1 = new Alumno();
            a1.deleteContact(contactoId);

            this.refrescarContactos();
            this.limpiarCampos();
        }
        
        
        
    }//GEN-LAST:event_Btn_eliminarActionPerformed

    private void Btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cerrarActionPerformed
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_Btn_cerrarActionPerformed

    private void TxtField_buscarDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtField_buscarDniKeyTyped
char c = evt.getKeyChar();
if(c<'0'||c>'9') evt.consume();

    }//GEN-LAST:event_TxtField_buscarDniKeyTyped

    private void TxtField_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtField_nombreKeyTyped
       char car = evt.getKeyChar();       
if((car<'a' || car>'z') && (car<'A' || car>'Z')            
    && car !='á' //Minúsculas            
    && car !='é'           
    && car !='í'           
    && car !='ó'          
    && car !='ú'  
    && car !='Á' //Mayúsculas            
    && car !='É'           
    && car !='Í'           
    && car !='Ó'
    && car !='Ú'
    && car !='ñ'
    && car !='Ñ'    
    && (car!=(char)KeyEvent.VK_SPACE))
{     
  evt.consume();  

}

    }//GEN-LAST:event_TxtField_nombreKeyTyped

    private void TxtField_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtField_telefonoKeyTyped
char c= evt.getKeyChar();
if(c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_TxtField_telefonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alumno_Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alumno_Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alumno_Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alumno_Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alumno_Contactos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_buscarDni;
    private javax.swing.JButton Btn_cerrar;
    private javax.swing.JButton Btn_editar;
    private javax.swing.JButton Btn_eliminar;
    private javax.swing.JButton Btn_registrar;
    private javax.swing.JComboBox<String> CBox_vinculo;
    private javax.swing.JTable JTable_alumnos;
    private javax.swing.JTable JTable_contactos;
    private javax.swing.JTextField TxtField_buscarDni;
    private javax.swing.JTextField TxtField_nombre;
    private javax.swing.JTextField TxtField_telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
