/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectopolilacolonia.Alumno;
import proyectopolilacolonia.MySql;
import proyectopolilacolonia.Observacion;

/**
 *
 * @author Pablo2
 */
public class Alumno_Observaciones extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    
    public Alumno_Observaciones() {
        initComponents();
        
        this.refrescarAlumnos();
        this.TxtField_observacionId.setVisible(false);
    }
    
    private void limpiar() {
        this.TxtField_dni.setText("");
        this.TxtField_buscarDni.setText("");
        this.TxtArea_observacion.setText("");
        this.TxtField_buscarDni.requestFocus();
    }
    
    private void refrescarAlumnos() {
        
        Alumno a1 = new Alumno();
        rs = a1.List();
        
        DefaultTableModel modelo = (DefaultTableModel) this.JTable_alumnos.getModel();
        modelo.setRowCount(0);
        int cantCols = modelo.getColumnCount();
        
        try {
            while(rs.next()) {
                Object[] fila = new Object[cantCols];
              
                fila[0] = rs.getObject(2);
                fila[1] = rs.getObject(4);
                fila[2] = rs.getObject(5);
                
                modelo.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Alumno_Observaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        
    }
    
    private void refrescarObservaciones() {
        
        Alumno a1 = new Alumno();
        String dni = this.TxtField_dni.getText().trim();
        
        rs = a1.listObservations(dni);
        
        DefaultTableModel modelo = (DefaultTableModel) this.JTable_observaciones.getModel();
        modelo.setRowCount(0);
        int cantCols = modelo.getColumnCount();
        
        try {
            while(rs.next()) {
                Object[] fila = new Object[cantCols];
                
                fila[0] = rs.getObject(1);
                fila[1] = rs.getObject(2);
                fila[2] = rs.getObject(3);
                fila[3] = rs.getObject(4);
                fila[4] = rs.getObject(5);
                
                modelo.addRow(fila);
                
            }
        } catch (Exception e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_alumnos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        TxtField_buscarDni = new javax.swing.JTextField();
        Btn_buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtArea_observacion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        TxtField_dni = new javax.swing.JTextField();
        Btn_registrar = new javax.swing.JButton();
        Btn_editar = new javax.swing.JButton();
        Btn_eliminar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTable_observaciones = new javax.swing.JTable();
        Btn_cerrar = new javax.swing.JButton();
        TxtField_observacionId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Listado de alumnos:");

        JTable_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DNI", "Nombre y apellido", "Fecha de nacimiento"
            }
        ));
        JTable_alumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_alumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable_alumnos);

        jLabel2.setText("DNI del alumno:");

        Btn_buscar.setText("Buscar");
        Btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_buscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Observación:");

        TxtArea_observacion.setColumns(20);
        TxtArea_observacion.setRows(5);
        jScrollPane2.setViewportView(TxtArea_observacion);

        jLabel4.setText("DNI del alumno seleccionado:");

        TxtField_dni.setEnabled(false);

        Btn_registrar.setText("Registrar observacion");
        Btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_registrarActionPerformed(evt);
            }
        });

        Btn_editar.setText("Editar");
        Btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_editarActionPerformed(evt);
            }
        });

        Btn_eliminar.setText("Eliminar");
        Btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_eliminarActionPerformed(evt);
            }
        });

        JTable_observaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nº", "Nombre y apellido del alumno", "Observación", "Fecha de creación", "Fecha de modificación"
            }
        ));
        JTable_observaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_observacionesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(JTable_observaciones);

        Btn_cerrar.setText("Cerrar");
        Btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cerrarActionPerformed(evt);
            }
        });

        TxtField_observacionId.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtField_buscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtField_dni))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(86, 86, 86)
                                .addComponent(TxtField_observacionId, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Btn_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtField_buscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtField_observacionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_registrar)
                    .addComponent(Btn_editar)
                    .addComponent(Btn_eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTable_alumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_alumnosMouseClicked
        int fila = this.JTable_alumnos.getSelectedRow();
        String dni = this.JTable_alumnos.getValueAt(fila, 0).toString();
        this.TxtField_dni.setText(dni);
        
        this.refrescarObservaciones();
    }//GEN-LAST:event_JTable_alumnosMouseClicked

    private void Btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_registrarActionPerformed
        Alumno a1 = new Alumno();
        Alumno a2 = new Alumno();
        Observacion o1 = new Observacion();
        String dni = this.TxtField_dni.getText().trim();
        o1.setObservacion(this.TxtArea_observacion.getText().trim());
        o1.setCreated_at(LocalDateTime.now());
        o1.setUpdated_at(LocalDateTime.now());
        a1 = a1.find(dni);
        
        a1.saveObservation(a1.getId(), o1);
        
        this.refrescarObservaciones();
    }//GEN-LAST:event_Btn_registrarActionPerformed

    private void JTable_observacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_observacionesMouseClicked
        int fila = JTable_observaciones.getSelectedRow();
        String observacion = JTable_observaciones.getValueAt(fila, 2).toString();
        
        this.TxtArea_observacion.setText(observacion);
        
    }//GEN-LAST:event_JTable_observacionesMouseClicked

    private void Btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_editarActionPerformed
        Alumno a1 = new Alumno();
        Observacion o1 = new Observacion();
        int fila = this.JTable_observaciones.getSelectedRow();
        int observacionId = Integer.valueOf(this.JTable_observaciones.getValueAt(fila, 0).toString());
        
        o1.setId(observacionId);
        o1.setObservacion(this.TxtArea_observacion.getText().trim());
        o1.setUpdated_at(LocalDateTime.now());
        
        a1.updateObservation(o1);
        
        this.refrescarObservaciones();
    }//GEN-LAST:event_Btn_editarActionPerformed

    private void Btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_eliminarActionPerformed
        int resultado = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres eliminar esta observación?", "Eliminar observación", JOptionPane.YES_NO_OPTION);
        if(resultado == JOptionPane.YES_NO_OPTION) {
            Alumno a1 = new Alumno();
            int fila = this.JTable_observaciones.getSelectedRow();
            int observacionId = Integer.valueOf(this.JTable_observaciones.getValueAt(fila, 0).toString());

            a1.deleteObservation(observacionId);

            this.refrescarObservaciones();
        }
        
        
    }//GEN-LAST:event_Btn_eliminarActionPerformed

    private void Btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_buscarActionPerformed
        int cantRows = this.JTable_alumnos.getModel().getRowCount();
        int cantCols = this.JTable_alumnos.getModel().getColumnCount();
        String dni = this.TxtField_buscarDni.getText().trim();
        
        for(int i=0; i < cantRows; i++) {
            for(int j=0; j < cantCols; j++) {
                if(this.JTable_alumnos.getValueAt(i, j).toString().equalsIgnoreCase(dni)) {
                    this.JTable_alumnos.setRowSelectionInterval(i, i);
                }
            }
        }
                
        
        
    }//GEN-LAST:event_Btn_buscarActionPerformed

    private void Btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cerrarActionPerformed
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_Btn_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alumno_Observaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alumno_Observaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alumno_Observaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alumno_Observaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alumno_Observaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_buscar;
    private javax.swing.JButton Btn_cerrar;
    private javax.swing.JButton Btn_editar;
    private javax.swing.JButton Btn_eliminar;
    private javax.swing.JButton Btn_registrar;
    private javax.swing.JTable JTable_alumnos;
    private javax.swing.JTable JTable_observaciones;
    private javax.swing.JTextArea TxtArea_observacion;
    private javax.swing.JTextField TxtField_buscarDni;
    private javax.swing.JTextField TxtField_dni;
    private javax.swing.JTextField TxtField_observacionId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
