/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.PlainDocument;
import proyectopolilacolonia.Alumno;

/**
 *
 * @author Pablo2
 */
public class Alumno_CRUD extends javax.swing.JFrame {

    private ResultSet rs = null;
    private ResultSetMetaData rsmd = null;
    
    public Alumno_CRUD() {
        initComponents();
        
        this.BtnGroup_sexo.add(RButton_masculino);
        this.BtnGroup_sexo.add(RButton_femenino);
        this.BtnGroup_sexo.add(RButton_otro);
        this.RButton_masculino.setSelected(true);
        
        this.limpiar();
        this.RefrescarTabla();
        
    }
    
    private void RefrescarTabla() {
        
        Alumno alumno = new Alumno();
        rs = alumno.List();

        DefaultTableModel modelo = (DefaultTableModel) JTable_alumnos.getModel();
        modelo.setRowCount(0);
        
        
        int cantCols = 6;
        try {
            
            while(rs.next()) {
                
                Object[] fila = new Object[cantCols];
                
                fila[0] = rs.getObject(1);
                fila[1] = rs.getObject(3);
                fila[2] = rs.getObject(4);
                fila[3] = rs.getObject(5);
                fila[4] = rs.getObject(6);
                fila[5] = rs.getObject(7);
                
                modelo.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Alumno_CRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void limpiar() {
        
        this.TxtField_dni.setText("");
        this.TxtField_nombre.setText("");
        this.RButton_masculino.setSelected(true);
        this.Dpicker_fecha.setDate(null);
        this.TxtField_nombre.requestFocus();
        
        
    }
    
    private void validarCampos(String dni, String nombre) {
//        String regexDni = "^[1-9]";
//        String regexNombre = "^[aA-zZ]+\\s*";
//        
//        if(!regexDni.matches(dni)) {
//            JOptionPane.showMessageDialog(this, "¡El campo DNI solo puede tener números!", "¡Error!", JOptionPane.ERROR_MESSAGE);
//        }
//        
//        if(!regexNombre.matches(nombre)) {
//            JOptionPane.showMessageDialog(this, "¡El campo nombre solo puede tener letras!", "¡Error!", JOptionPane.ERROR_MESSAGE);
//        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroup_sexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtField_nombre = new javax.swing.JTextField();
        TxtField_dni = new javax.swing.JTextField();
        RButton_masculino = new javax.swing.JRadioButton();
        RButton_femenino = new javax.swing.JRadioButton();
        RButton_otro = new javax.swing.JRadioButton();
        Dpicker_fecha = new org.jdesktop.swingx.JXDatePicker();
        Btn_registrar = new javax.swing.JButton();
        Btn_editar = new javax.swing.JButton();
        Btn_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_alumnos = new javax.swing.JTable();
        Btn_cerrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TxtField_buscarPorDni = new javax.swing.JTextField();
        Btn_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre y apellido: (Editable)");

        jLabel2.setText("DNI:");

        jLabel3.setText("Sexo: (Editable)");

        jLabel4.setText("Fecha de nacimiento: (Editable)");

        RButton_masculino.setText("Masculino");

        RButton_femenino.setText("Femenino");

        RButton_otro.setText("Otro");

        Btn_registrar.setText("Registrar");
        Btn_registrar.setToolTipText("Registrar un nuevo alumno");
        Btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_registrarActionPerformed(evt);
            }
        });

        Btn_editar.setText("Editar");
        Btn_editar.setToolTipText("Editar un alumno existente");
        Btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_editarActionPerformed(evt);
            }
        });

        Btn_eliminar.setText("Eliminar");
        Btn_eliminar.setToolTipText("Borrar un alumno existente");
        Btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_eliminarActionPerformed(evt);
            }
        });

        JTable_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Dni", "Nombre y apellido", "Fecha de nacimiento", "Sexo", "Fecha de registro", "Ultima vez modificado"
            }
        ));
        JTable_alumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_alumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable_alumnos);

        Btn_cerrar.setText("Cerrar");
        Btn_cerrar.setToolTipText("Cerrar formulario");
        Btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cerrarActionPerformed(evt);
            }
        });

        jLabel5.setText("Buscar alumnos por DNI:");

        Btn_buscar.setText("Buscar");
        Btn_buscar.setToolTipText("Buscar un alumno en el listado por el DNI.");
        Btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtField_nombre)
                            .addComponent(TxtField_dni)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RButton_masculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RButton_femenino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RButton_otro)
                                .addGap(0, 85, Short.MAX_VALUE))
                            .addComponent(Dpicker_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(Btn_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_registrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_eliminar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtField_buscarPorDni, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RButton_masculino)
                    .addComponent(RButton_femenino)
                    .addComponent(RButton_otro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Dpicker_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_registrar)
                    .addComponent(Btn_editar)
                    .addComponent(Btn_eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtField_buscarPorDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_registrarActionPerformed
        if(this.TxtField_nombre.getText() == "" || this.TxtField_dni.getText() == "" || this.Dpicker_fecha.getDate() == null) {
            JOptionPane.showMessageDialog(this, "¡Todos los campos son obligatorios!", "¡Error!", JOptionPane.ERROR_MESSAGE);
        } else {
//            this.validarCampos(TxtField_dni.getText().trim(), TxtField_nombre.getText().trim());
            
            
            Alumno alumno = new Alumno();
            String codTarjeta = this.TxtField_dni.getText().trim() + this.TxtField_nombre.getText().trim();
            LocalDate fechaNacimiento = this.Dpicker_fecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            //LocalDate fechaNacimiento = LocalDate.now();
            alumno.setDni(this.TxtField_dni.getText().trim());
            alumno.setCodTarjeta(codTarjeta);
            alumno.setNombreCompleto(this.TxtField_nombre.getText().trim());
            alumno.setFechaNacimiento(fechaNacimiento);
            
            if(this.RButton_masculino.isSelected()) {
                alumno.setSexo(this.RButton_masculino.getText());
            } else if (this.RButton_femenino.isSelected()) {
                alumno.setSexo(this.RButton_femenino.getText());
            } else {
                alumno.setSexo(this.RButton_otro.getText());
            }
            
            alumno.setCreated_at(LocalDateTime.now());
            alumno.setUpdated_at(LocalDateTime.now());
            
            alumno.save(alumno);
            
            this.RefrescarTabla();
            
        }
    }//GEN-LAST:event_Btn_registrarActionPerformed

    private void JTable_alumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_alumnosMouseClicked
        int fila = this.JTable_alumnos.getSelectedRow();
        String dni = this.JTable_alumnos.getValueAt(fila, 0).toString();
        Alumno a1 = new Alumno();
        Alumno a2 = new Alumno();
        
        a2 = a1.find(dni);
        this.TxtField_dni.setText(a2.getDni());
        this.TxtField_nombre.setText(a2.getNombreCompleto());
        
        if(a2.getSexo().equalsIgnoreCase("Masculino")) {
            
            this.RButton_masculino.setSelected(true);
        } else if(a2.getSexo().equalsIgnoreCase("Femenino")) {
            
            this.RButton_femenino.setSelected(true);
        } else {
            this.RButton_otro.setSelected(true);
        }
        
        this.Dpicker_fecha.setDate(Date.valueOf(a2.getFechaNacimiento()));
        
    }//GEN-LAST:event_JTable_alumnosMouseClicked

    private void Btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cerrarActionPerformed
        this.limpiar();
        this.dispose();
        this.setVisible(false);
        
    }//GEN-LAST:event_Btn_cerrarActionPerformed

    private void Btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_editarActionPerformed
        Alumno a1 = new Alumno();
        a1.setNombreCompleto(this.TxtField_nombre.getText().trim());
        a1.setDni(this.TxtField_dni.getText().trim());
        a1.setFechaNacimiento(this.Dpicker_fecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        
        if(this.RButton_masculino.isSelected()) {
            a1.setSexo(this.RButton_masculino.getText());
        } else if (this.RButton_femenino.isSelected()) {
            a1.setSexo(this.RButton_femenino.getText());
        } else {
            a1.setSexo(this.RButton_otro.getText());
        }
        
        a1.setUpdated_at(LocalDateTime.now());
        
        a1.update(a1);
        
        this.RefrescarTabla();
        this.limpiar();
    }//GEN-LAST:event_Btn_editarActionPerformed

    private void Btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_eliminarActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "¿Estas seguro que quieres eliminar este usuario?");
        if(result == JOptionPane.YES_NO_OPTION) {
            String dni = this.TxtField_dni.getText().trim();
            Alumno a1 = new Alumno();
            a1.delete(dni);
            this.RefrescarTabla();
            this.limpiar();
        }
    }//GEN-LAST:event_Btn_eliminarActionPerformed

    private void Btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_buscarActionPerformed
        String dni = this.TxtField_buscarPorDni.getText().trim();
        int cantRows = this.JTable_alumnos.getModel().getRowCount();
        int cantCols = this.JTable_alumnos.getModel().getColumnCount();
        
        for(int i=0; i < cantRows; i++) {
            for(int j=0; j < cantCols; j++) {
                if(this.JTable_alumnos.getValueAt(i, j).toString().equalsIgnoreCase(dni)) {
                    this.JTable_alumnos.setRowSelectionInterval(i, i);
                    
                }
                
            }
        }
    }//GEN-LAST:event_Btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alumno_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alumno_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alumno_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alumno_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alumno_CRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGroup_sexo;
    private javax.swing.JButton Btn_buscar;
    private javax.swing.JButton Btn_cerrar;
    private javax.swing.JButton Btn_editar;
    private javax.swing.JButton Btn_eliminar;
    private javax.swing.JButton Btn_registrar;
    private org.jdesktop.swingx.JXDatePicker Dpicker_fecha;
    private javax.swing.JTable JTable_alumnos;
    private javax.swing.JRadioButton RButton_femenino;
    private javax.swing.JRadioButton RButton_masculino;
    private javax.swing.JRadioButton RButton_otro;
    private javax.swing.JTextField TxtField_buscarPorDni;
    private javax.swing.JTextField TxtField_dni;
    private javax.swing.JTextField TxtField_nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
