/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Moron
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        JMenuItem_Alumnos_CRUD = new javax.swing.JMenuItem();
        JMenuItem_Alumno_Observaciones = new javax.swing.JMenuItem();
        JMenuItem_Alumno_Contactos = new javax.swing.JMenuItem();
        JMenuItem_Profesores_CRUD = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        JMenuItem_Deportes_CRUD = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Alumnos...");

        JMenuItem_Alumnos_CRUD.setText("Registrar, actualizar, eliminar...");
        JMenuItem_Alumnos_CRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_Alumnos_CRUDActionPerformed(evt);
            }
        });
        jMenu3.add(JMenuItem_Alumnos_CRUD);

        JMenuItem_Alumno_Observaciones.setText("Observaciones...");
        JMenuItem_Alumno_Observaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_Alumno_ObservacionesActionPerformed(evt);
            }
        });
        jMenu3.add(JMenuItem_Alumno_Observaciones);

        JMenuItem_Alumno_Contactos.setText("Contactos...");
        JMenuItem_Alumno_Contactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_Alumno_ContactosActionPerformed(evt);
            }
        });
        jMenu3.add(JMenuItem_Alumno_Contactos);

        jMenuBar1.add(jMenu3);

        JMenuItem_Profesores_CRUD.setText("Profesores...");

        jMenuItem1.setText("Registrar, editar, eliminar...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JMenuItem_Profesores_CRUD.add(jMenuItem1);

        jMenuBar1.add(JMenuItem_Profesores_CRUD);

        jMenu4.setText("Deportes y categorías...");

        JMenuItem_Deportes_CRUD.setText("Registrar, eliminar deportes...");
        JMenuItem_Deportes_CRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_Deportes_CRUDActionPerformed(evt);
            }
        });
        jMenu4.add(JMenuItem_Deportes_CRUD);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuItem_Alumnos_CRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_Alumnos_CRUDActionPerformed
        Alumno_CRUD a1 = new Alumno_CRUD();
        a1.setLocationRelativeTo(null);
        a1.setVisible(true);
    }//GEN-LAST:event_JMenuItem_Alumnos_CRUDActionPerformed

    private void JMenuItem_Alumno_ObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_Alumno_ObservacionesActionPerformed
        Alumno_Observaciones ao1 = new Alumno_Observaciones();
        ao1.setLocationRelativeTo(null);
        ao1.setVisible(true);
    }//GEN-LAST:event_JMenuItem_Alumno_ObservacionesActionPerformed

    private void JMenuItem_Alumno_ContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_Alumno_ContactosActionPerformed
        Alumno_Contactos ac1 = new Alumno_Contactos();
        ac1.setLocationRelativeTo(null);
        ac1.setVisible(true);
    }//GEN-LAST:event_JMenuItem_Alumno_ContactosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Profesor_CRUD pc1 = new Profesor_CRUD();
        pc1.setLocationRelativeTo(null);
        pc1.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void JMenuItem_Deportes_CRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_Deportes_CRUDActionPerformed
        Deporte_CRUD dc1 = new Deporte_CRUD();
        dc1.setLocationRelativeTo(null);
        dc1.setVisible(true);
    }//GEN-LAST:event_JMenuItem_Deportes_CRUDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuItem_Alumno_Contactos;
    private javax.swing.JMenuItem JMenuItem_Alumno_Observaciones;
    private javax.swing.JMenuItem JMenuItem_Alumnos_CRUD;
    private javax.swing.JMenuItem JMenuItem_Deportes_CRUD;
    private javax.swing.JMenu JMenuItem_Profesores_CRUD;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
