/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectopolilacolonia.Profesor;

/**
 *
 * @author Pablo2
 */
public class Profesor_CRUD extends javax.swing.JFrame {

    private ResultSet rs = null;
    
    public Profesor_CRUD() {
        initComponents();
        this.BtnGroup_sexo.add(RButton_masculino);
        this.BtnGroup_sexo.add(RButton_femenino);
        this.BtnGroup_sexo.add(RButton_otro);
        
        this.RButton_masculino.setSelected(true);
        this.refrescarProfesores();
        
    }
    
    private void refrescarProfesores() {
        Profesor p = new Profesor();
        rs = p.list();
        DefaultTableModel modelo = (DefaultTableModel) this.JTable_profesores.getModel();
        modelo.setRowCount(0);
        int cantCols = modelo.getColumnCount();
        
        try {
            while(rs.next()) {
                Object[] fila = new Object[cantCols];
            
                fila[0] = rs.getObject(2);
                fila[1] = rs.getObject(4);
                fila[2] = rs.getObject(5);
                fila[3] = rs.getObject(6);
                fila[4] = rs.getObject(7);
                fila[5] = rs.getObject(8);

                modelo.addRow(fila);
            }
            
            
        } catch (Exception e) {
        }
    }
    
    private void limpiar() {
        this.TxtField_dni.setText("");
        this.TxtField_nombre.setText("");
        //this.JDPicker_fechaNacimiento.setDate(null);
        this.RButton_masculino.setSelected(true);
        this.TxtField_buscarDni.setText("");
        
        this.TxtField_nombre.setRequestFocusEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroup_sexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtField_nombre = new javax.swing.JTextField();
        TxtField_dni = new javax.swing.JTextField();
        RButton_masculino = new javax.swing.JRadioButton();
        RButton_femenino = new javax.swing.JRadioButton();
        RButton_otro = new javax.swing.JRadioButton();
        Btn_registrar = new javax.swing.JButton();
        Btn_editar = new javax.swing.JButton();
        Btn_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_profesores = new javax.swing.JTable();
        Btn_cerrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TxtField_buscarDni = new javax.swing.JTextField();
        Btn_buscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CBox_año = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        CBox_mes = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        CBox_dia = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre y apellido: (Editable)");

        jLabel2.setText("DNI:");

        jLabel3.setText("Sexo: (Editable)");

        jLabel4.setText("Fecha de nacimiento: (Editable)");

        TxtField_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtField_nombreKeyTyped(evt);
            }
        });

        TxtField_dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtField_dniKeyTyped(evt);
            }
        });

        RButton_masculino.setText("Masculino");

        RButton_femenino.setText("Femenino");

        RButton_otro.setText("Otro");

        Btn_registrar.setText("Registrar");
        Btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_registrarActionPerformed(evt);
            }
        });

        Btn_editar.setText("Editar");
        Btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_editarActionPerformed(evt);
            }
        });

        Btn_eliminar.setText("Eliminar");
        Btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_eliminarActionPerformed(evt);
            }
        });

        JTable_profesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre y apellido", "Fecha de nacimiento", "Sexo", "Registrado el día...", "Editado por última vez..."
            }
        ));
        JTable_profesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_profesoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable_profesores);

        Btn_cerrar.setText("Cerrar");

        jLabel5.setText("Buscar por DNI en el listado:");

        TxtField_buscarDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtField_buscarDniKeyTyped(evt);
            }
        });

        Btn_buscar.setText("Buscar");
        Btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_buscarActionPerformed(evt);
            }
        });

        jLabel6.setText("Año:");

        CBox_año.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));
        CBox_año.setSelectedIndex(30);

        jLabel7.setText("Mes:");

        CBox_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel8.setText("Día:");

        CBox_dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtField_nombre)
                            .addComponent(TxtField_dni)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RButton_masculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RButton_femenino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RButton_otro)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CBox_año, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CBox_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBox_dia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(TxtField_buscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RButton_masculino)
                    .addComponent(RButton_femenino)
                    .addComponent(RButton_otro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(CBox_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(CBox_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(CBox_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_registrar)
                    .addComponent(Btn_editar)
                    .addComponent(Btn_eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtField_buscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_registrarActionPerformed
        
        if(this.TxtField_nombre.getText() == "" || this.TxtField_dni.getText() == "" /*|| this.JDPicker_fechaNacimiento.getDate()==null*/) {
            JOptionPane.showMessageDialog(this, "¡Los campos no pueden estar vacios!", "¡Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            
            Profesor p = new Profesor();
            p.setNombreCompleto(this.TxtField_nombre.getText().trim());
            p.setDni(this.TxtField_dni.getText().trim());
            String codTarjeta = this.TxtField_nombre.getText().trim()+this.TxtField_dni.getText().trim();
            p.setCodTarjeta(codTarjeta);
            
            if(this.RButton_masculino.isSelected()) {
                p.setSexo(this.RButton_masculino.getText());
            } else if(this.RButton_femenino.isSelected()) {
                p.setSexo(this.RButton_femenino.getText());
            } else {
                p.setSexo(this.RButton_otro.getText());
            }
            int ano = Integer.valueOf(this.CBox_año.getSelectedItem().toString());
            int mes = 1;
            int dia = Integer.valueOf(this.CBox_dia.getSelectedItem().toString());
            
            switch(this.CBox_mes.getSelectedItem().toString()) {
                case "Enero":mes=1;
                break;
                case "Febrero":mes=2;
                break;
                case "Marzo":mes=3;
                break;
                case "Abril":mes=4;
                break;
                case "Mayo":mes=5;
                break;
                case "Junio":mes=6;
                break;
                case "Julio":mes=7;
                break;
                case "Agosto":mes=8;
                break;
                case "Septiembre":mes=9;
                break;
                case "Octubre":mes=10;
                break;
                case "Noviembre":mes=11;
                break;
                case "Diciembre":mes=12;
                break;
            }
            p.setFechaNacimiento(LocalDate.of(ano,mes,dia));
            //p.setFechaNacimiento(this.JDPicker_fechaNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            p.setCreated_at(LocalDateTime.now());
            p.setUpdated_at(LocalDateTime.now());
            
            
            p.save(p);
            
            this.refrescarProfesores();
            this.limpiar();
        }
       
        
    }//GEN-LAST:event_Btn_registrarActionPerformed

    private void Btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_editarActionPerformed
        if(this.TxtField_nombre.getText() == "" || this.TxtField_dni.getText() == "" /*|| this.JDPicker_fechaNacimiento.getDate()==null*/) {
            
        } else {
            Profesor p = new Profesor();
            int fila = this.JTable_profesores.getSelectedRow();
            
            p.setDni(this.JTable_profesores.getValueAt(fila, 0).toString());
            p.setNombreCompleto(this.TxtField_nombre.getText().trim());
          
            if(this.RButton_masculino.isSelected()) {
                p.setSexo(this.RButton_masculino.getText());
            } else if(this.RButton_femenino.isSelected()) {
                p.setSexo(this.RButton_femenino.getText());
            } else {
                p.setSexo(this.RButton_otro.getText());
            }
            
            int ano = Integer.valueOf(this.CBox_año.getSelectedItem().toString());
        int dia = Integer.valueOf(this.CBox_dia.getSelectedItem().toString());
        int mes = 0;
        
        switch(this.CBox_mes.getSelectedItem().toString()) {
                case "Enero":mes=1;
                break;
                case "Febrero":mes=2;
                break;
                case "Marzo":mes=3;
                break;
                case "Abril":mes=4;
                break;
                case "Mayo":mes=5;
                break;
                case "Junio":mes=6;
                break;
                case "Julio":mes=7;
                break;
                case "Agosto":mes=8;
                break;
                case "Septiembre":mes=9;
                break;
                case "Octubre":mes=10;
                break;
                case "Noviembre":mes=11;
                break;
                case "Diciembre":mes=12;
                break;
            }
        
            LocalDate fechaNacimiento = LocalDate.of(ano, mes, dia);
            p.setFechaNacimiento(fechaNacimiento);
            //p.setFechaNacimiento(this.JDPicker_fechaNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            p.setUpdated_at(LocalDateTime.now());
            p.update(p);
            
            this.refrescarProfesores();
            this.limpiar();
        }
    }//GEN-LAST:event_Btn_editarActionPerformed

    private void Btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_eliminarActionPerformed
        int resultado = JOptionPane.showConfirmDialog(this, "¿Estas seguro de que quieres eliminar este profesor?", "Eliminar", JOptionPane.YES_NO_OPTION);
        if(resultado == JOptionPane.YES_NO_OPTION) {
            int fila = this.JTable_profesores.getSelectedRow();
            String dni = this.JTable_profesores.getValueAt(fila, 0).toString();
            Profesor p = new Profesor();
            p = p.find(dni);
            p.delete(p.getId()); 
            
            this.refrescarProfesores();
            this.limpiar();
        }
        
        
    }//GEN-LAST:event_Btn_eliminarActionPerformed

    private void JTable_profesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_profesoresMouseClicked
        int fila = this.JTable_profesores.getSelectedRow();
        String dni = this.JTable_profesores.getValueAt(fila, 0).toString();
        String nombre = this.JTable_profesores.getValueAt(fila, 1).toString();
        Date fechaNacimiento = Date.valueOf(this.JTable_profesores.getValueAt(fila, 2).toString());
        String sexo = this.JTable_profesores.getValueAt(fila, 3).toString();
        
        this.TxtField_dni.setText(dni);
        this.TxtField_nombre.setText(nombre);
        //this.JDPicker_fechaNacimiento.setDate(fechaNacimiento);
        
        if(sexo.equalsIgnoreCase("masculino")) {
            this.RButton_masculino.setSelected(true);
        } else if(sexo.equalsIgnoreCase("femenino")) {
            this.RButton_femenino.setSelected(true);
        } else {
            this.RButton_otro.setSelected(true);
        }
        
        String fecha = fechaNacimiento.toString();
        String[] fechas = fecha.split("-");
        this.CBox_año.setSelectedItem(fechas[0]);
        this.CBox_dia.setSelectedItem(fechas[2]);
        switch(fechas[1]) {
            case "01": this.CBox_mes.setSelectedIndex(0);
            break;
            case "02": this.CBox_mes.setSelectedIndex(1);
            break;
            case "03": this.CBox_mes.setSelectedIndex(2);
            break;
            case "04": this.CBox_mes.setSelectedIndex(3);
            break;
            case "05": this.CBox_mes.setSelectedIndex(4);
            break;
            case "06": this.CBox_mes.setSelectedIndex(5);
            break;
            case "07": this.CBox_mes.setSelectedIndex(6);
            break;
            case "08": this.CBox_mes.setSelectedIndex(7);
            break;
            case "09": this.CBox_mes.setSelectedIndex(8);
            break;
            case "10": this.CBox_mes.setSelectedIndex(9);
            break;
            case "11": this.CBox_mes.setSelectedIndex(10);
            break;
            case "12": this.CBox_mes.setSelectedIndex(11);
            break;
        }
        
    }//GEN-LAST:event_JTable_profesoresMouseClicked

    private void Btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_buscarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) this.JTable_profesores.getModel();
        
        for (int i = 0; i < modelo.getRowCount(); i++) {
            for (int j = 0; j < modelo.getColumnCount(); j++) {
                if(JTable_profesores.getValueAt(i, 0).toString().equalsIgnoreCase(this.TxtField_buscarDni.getText().trim())) {
                    JTable_profesores.setRowSelectionInterval(i, i);
                }
            }
        }
        
        this.limpiar();
    }//GEN-LAST:event_Btn_buscarActionPerformed

    private void TxtField_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtField_nombreKeyTyped
             char car = evt.getKeyChar();       
if((car<'a' || car>'z') && (car<'A' || car>'Z')            
    && car !='á' //Minúsculas            
    && car !='é'           
    && car !='í'           
    && car !='ó'          
    && car !='ú'  
    && car !='Á' //Mayúsculas            
    && car !='É'           
    && car !='Í'           
    && car !='Ó'
    && car !='Ú'
    && car !='ñ'
    && car !='Ñ'    
    && (car!=(char)KeyEvent.VK_SPACE))
{     
  evt.consume();  

}
    }//GEN-LAST:event_TxtField_nombreKeyTyped

    private void TxtField_dniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtField_dniKeyTyped
char c = evt.getKeyChar();
if(c<'0'||c>'9') evt.consume();
     
    }//GEN-LAST:event_TxtField_dniKeyTyped

    private void TxtField_buscarDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtField_buscarDniKeyTyped
       char c = evt.getKeyChar();
if(c<'0'||c>'9') evt.consume();

    }//GEN-LAST:event_TxtField_buscarDniKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profesor_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profesor_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profesor_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profesor_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profesor_CRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGroup_sexo;
    private javax.swing.JButton Btn_buscar;
    private javax.swing.JButton Btn_cerrar;
    private javax.swing.JButton Btn_editar;
    private javax.swing.JButton Btn_eliminar;
    private javax.swing.JButton Btn_registrar;
    private javax.swing.JComboBox<String> CBox_año;
    private javax.swing.JComboBox<String> CBox_dia;
    private javax.swing.JComboBox<String> CBox_mes;
    private javax.swing.JTable JTable_profesores;
    private javax.swing.JRadioButton RButton_femenino;
    private javax.swing.JRadioButton RButton_masculino;
    private javax.swing.JRadioButton RButton_otro;
    private javax.swing.JTextField TxtField_buscarDni;
    private javax.swing.JTextField TxtField_dni;
    private javax.swing.JTextField TxtField_nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
